//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.Sessions = new HashSet<Sessions>();
        }
    
        public int Id { get; set; }
        public int Location_Id { get; set; }
        public string Name { get; set; }
    
        public virtual Locations Locations { get; set; }
        public virtual ICollection<Sessions> Sessions { get; set; }
    }
}
