//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public Sessions()
        {
            this.Bookings = new HashSet<Bookings>();
        }
    
        public int Id { get; set; }
        public int Room_Id { get; set; }
        public System.DateTime Date_Time { get; set; }
        public bool Is_Full { get; set; }
        public bool Is_Active { get; set; }
    
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
